# Generated by Django 6.1 on 2026-08-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AiProject'),
        ),
        migrations.AlterField(
            model_name='aiproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Article'),
        ),
    ]
