# Generated by Django 6.1 on 2026-08-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_aiproject_image_alter_aiproject_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='AiProject'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='Article/'),
        ),
    ]
