# Generated by Django 6.1 on 2026-08-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coment',
            new_name='Contacts',
        ),
    ]
