# Generated by Django 6.1 on 2026-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
