# Generated by Django 6.1 on 2026-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_socialmedia_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('skill1', models.TextField()),
                ('skill2', models.TextField()),
                ('skill3', models.TextField()),
                ('skill4', models.TextField()),
                ('skill5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description2', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
