# Generated by Django 6.1 on 2026-08-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_aboutme_experience_delete_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description2',
            new_name='description',
        ),
    ]
