# Generated by Django 6.1 on 2026-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_description2_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField()),
                ('description2', models.TextField(blank=True)),
                ('skill1', models.CharField(blank=True, max_length=100)),
                ('skill2', models.CharField(blank=True, max_length=100)),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('skill5', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='aboutme',
        ),
    ]
