# Generated by Django 6.1 on 2026-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_about_delete_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproject',
            name='link',
        ),
    ]
